
services:
  backend:
    build:
      context: ./Sign_Language_Converter
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"